apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNMariaDB
metadata:
  name: mariadb-1
spec:
  parameters:
    service:
      version: "11.8"
      access:
        - user: first-customer
          writeConnectionSecretToRef:
            name: first-customer-mariadb-creds
            namespace: {{ .Release.Namespace }}
    size:
      plan: standard-2
  writeConnectionSecretToRef:
    name: mariadb-creds
